/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Asset, Transaction } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    corretora: 'Banco BMG',
    displayName: 'CDB de 110.0% do CDI',
    observacao: 'SUPER POUP BMG',
    valorAnterior: 8458.64,
    valorAtual: 8658.64,
    valorizacao: 200.00, // positive BRL valuation
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '11/05/2026',
    mesReferencia: 'Maio',
    alerta: true
  },
  {
    id: 'asset-2',
    corretora: 'Banco BMG',
    displayName: 'CDB Escalolado 110.0% CDI',
    observacao: 'CDB ESCALONADO',
    valorAnterior: 21657.85,
    valorAtual: 22365.39,
    valorizacao: 707.54,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '29/08/2027',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-3',
    corretora: 'Banco BMG',
    displayName: 'CDB de 112.0% do CDI',
    observacao: 'CDB ESCALONADO',
    valorAnterior: 36624.10,
    valorAtual: 38442.11,
    valorizacao: 1818.01,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '01/04/2030',
    mesReferencia: 'Abril',
    alerta: false
  },
  {
    id: 'asset-4',
    corretora: 'Banco BMG',
    displayName: 'CDB do CDI de 112.0%',
    observacao: 'CDB ESCALONADO',
    valorAnterior: 34297.11,
    valorAtual: 35995.10,
    valorizacao: 1697.99,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '02/04/2030',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-5',
    corretora: 'Banco BMG',
    displayName: 'CDB de 106.0% do CDI',
    observacao: 'CDB ESCALONADO',
    valorAnterior: 21467.37,
    valorAtual: 22151.68,
    valorizacao: 684.31,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '15/09/2030',
    mesReferencia: 'Junho',
    alerta: false
  },
  {
    id: 'asset-6',
    corretora: 'Nubank',
    displayName: 'CDB Reserva Familiar 100% CDI',
    observacao: 'Saldo Separado',
    valorAnterior: 64921.33,
    valorAtual: 64921.33,
    valorizacao: 0.00,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '01/01/2050',
    mesReferencia: 'Maio',
    alerta: true
  },
  {
    id: 'asset-7',
    corretora: 'Nubank',
    displayName: 'LCA Banco ABC do Brasil 90.5%',
    observacao: 'LCA BANCO ABC BRASIL',
    valorAnterior: 5357.97,
    valorAtual: 5404.85,
    valorizacao: 46.88,
    tipo: 'Renda Fixa',
    subtipo: 'LCA',
    vencimento: '01/07/2026',
    mesReferencia: 'Julho',
    alerta: false
  },
  {
    id: 'asset-8',
    corretora: 'Nubank',
    displayName: 'CDB 11.29% a.a. Digimais',
    observacao: 'CDB BANCO DIGIMAIS',
    valorAnterior: 4666.91,
    valorAtual: 5001.24,
    valorizacao: 334.33,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '09/07/2026',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-9',
    corretora: 'Nubank',
    displayName: 'CDB de 113.0% do CDI Semear',
    observacao: 'CDB DM FINANCEIRA',
    valorAnterior: 3431.30,
    valorAtual: 3537.06,
    valorizacao: 105.76,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '03/05/2027',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-10',
    corretora: 'Nubank',
    displayName: 'CDB de 122.0% do CDI Semear',
    observacao: 'CDB BANCO SEMEAR SA',
    valorAnterior: 3306.93,
    valorAtual: 3577.06,
    valorizacao: 270.13,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '03/06/2027',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-11',
    corretora: 'Nubank',
    displayName: 'LCA de 93.0% do CDI Original',
    observacao: 'LCA ORIGINAL',
    valorAnterior: 45782.66,
    valorAtual: 40120.25,
    valorizacao: -5662.41, // negative BRL valuation
    tipo: 'Renda Fixa',
    subtipo: 'LCA',
    vencimento: '04/05/2026',
    mesReferencia: 'Abril',
    alerta: true
  },
  {
    id: 'asset-12',
    corretora: 'Nubank',
    displayName: 'LCI de 91.5% do CDI',
    observacao: 'LCI BRB',
    valorAnterior: 18139.30,
    valorAtual: 18309.02,
    valorizacao: 169.72,
    tipo: 'Renda Fixa',
    subtipo: 'LCI',
    vencimento: '16/10/2026',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-13',
    corretora: 'Banco Inter',
    displayName: 'LCI IPCA + 5.28%',
    observacao: 'LCI IPCA FINAL 3 ANOS',
    valorAnterior: 3300.34,
    valorAtual: 3307.53,
    valorizacao: 7.19,
    tipo: 'Renda Fixa',
    subtipo: 'LCI',
    vencimento: '29/05/2026',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-14',
    corretora: 'Banco Inter',
    displayName: 'LCI de 96.0% do CDI',
    observacao: 'LCI ABC MENSAL',
    valorAnterior: 1978.65,
    valorAtual: 2008.21,
    valorizacao: 29.56,
    tipo: 'Renda Fixa',
    subtipo: 'LCI',
    vencimento: '12/06/2026',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-15',
    corretora: 'Nubank',
    displayName: 'CDB de 115.0% do CDI Arbi',
    observacao: 'CDB ARBI',
    valorAnterior: 11803.29,
    valorAtual: 12329.27,
    valorizacao: 525.98,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '12/01/2029',
    mesReferencia: 'Janeiro',
    alerta: false
  },
  {
    id: 'asset-16',
    corretora: 'Banco Inter',
    displayName: 'CDB de 87.0% do CDI Liquidez',
    observacao: 'LIG LIQUIDEZ',
    valorAnterior: 16023.26,
    valorAtual: 16165.79,
    valorizacao: 142.53,
    tipo: 'Renda Fixa',
    subtipo: 'CDB',
    vencimento: '03/09/2027',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-17',
    corretora: 'XP Investimentos',
    displayName: 'FII HGLG11 - Logística',
    observacao: 'HGLG Principal',
    valorAnterior: 22400.00,
    valorAtual: 23680.00,
    valorizacao: 1280.00,
    tipo: 'Renda Variável',
    subtipo: 'FII',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'HGLG11'
  },
  {
    id: 'asset-18',
    corretora: 'XP Investimentos',
    displayName: 'WEGE3 - WEG S.A.',
    observacao: 'Ações Ordinárias',
    valorAnterior: 18350.00,
    valorAtual: 19120.00,
    valorizacao: 770.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'WEGE3'
  },
  {
    id: 'asset-19',
    corretora: 'XP Investimentos',
    displayName: 'IVVB11 - S&P 500 ETF',
    observacao: 'Acompanhamento S&P',
    valorAnterior: 35600.00,
    valorAtual: 33810.00,
    valorizacao: -1790.00,
    tipo: 'Renda Variável',
    subtipo: 'ETF',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'IVVB11'
  },
  {
    id: 'asset-20',
    corretora: 'BTG Pactual',
    displayName: 'Fundo Alaska Black FIC FI',
    observacao: 'Fundo de Ações',
    valorAnterior: 45000.00,
    valorAtual: 42100.00,
    valorizacao: -2900.00,
    tipo: 'Fundos',
    subtipo: 'Ação',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Março',
    alerta: false
  },
  {
    id: 'asset-21',
    corretora: 'BTG Pactual',
    displayName: 'Fundo Kinea Atlas Multimercado',
    observacao: 'Fundo Multimercado FIM',
    valorAnterior: 50000.00,
    valorAtual: 51950.00,
    valorizacao: 1950.00,
    tipo: 'Fundos',
    subtipo: 'Multimercado',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-22',
    corretora: 'BTG Pactual',
    displayName: 'PETR4 - Petróleo Brasileiro S.A.',
    observacao: 'Ação Preferencial',
    valorAnterior: 14500.00,
    valorAtual: 15400.00,
    valorizacao: 900.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'PETR4'
  },
  {
    id: 'asset-23',
    corretora: 'Banco Inter',
    displayName: 'VALE3 - Vale S.A.',
    observacao: 'Ação Ordinária de Mineração',
    valorAnterior: 9800.00,
    valorAtual: 9350.00,
    valorizacao: -450.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'VALE3'
  },
  {
    id: 'asset-24',
    corretora: 'Nubank',
    displayName: 'FII MXRF11 - Maxi Renda',
    observacao: 'Fundo Imobiliário de Papel',
    valorAnterior: 6200.00,
    valorAtual: 6350.00,
    valorizacao: 150.00,
    tipo: 'Renda Variável',
    subtipo: 'FII',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'MXRF11'
  },
  {
    id: 'asset-25',
    corretora: 'BTG Pactual',
    displayName: 'BOVA11 - iShares Ibovespa ETF',
    observacao: 'ETF de Índice de referência',
    valorAnterior: 24000.00,
    valorAtual: 24650.00,
    valorizacao: 650.00,
    tipo: 'Renda Variável',
    subtipo: 'ETF',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'BOVA11'
  },
  {
    id: 'asset-26',
    corretora: 'XP Investimentos',
    displayName: 'XPML11 - XP Malls FII',
    observacao: 'Shoppings e Varejo',
    valorAnterior: 15200.00,
    valorAtual: 16100.00,
    valorizacao: 900.00,
    tipo: 'Renda Variável',
    subtipo: 'FII',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'XPML11'
  },
  {
    id: 'asset-27',
    corretora: 'Sofisa',
    displayName: 'CRA Rede D’Or 103% CDI',
    observacao: 'Certificado de Recebíveis do Agronegócio',
    valorAnterior: 10450.00,
    valorAtual: 10830.00,
    valorizacao: 380.00,
    tipo: 'Renda Fixa',
    subtipo: 'CRA',
    vencimento: '15/12/2028',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-28',
    corretora: 'Banco Inter',
    displayName: 'CRI Direcional Engenharia IPCA + 6.2%',
    observacao: 'Certificado de Recebíveis Imobiliários',
    valorAnterior: 8200.00,
    valorAtual: 8640.00,
    valorizacao: 440.00,
    tipo: 'Renda Fixa',
    subtipo: 'CRI',
    vencimento: '22/10/2029',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-29',
    corretora: 'Sofisa',
    displayName: 'Tesouro IPCA+ 2035',
    observacao: 'Tesouro Direto IPCA + 5.95%',
    valorAnterior: 12400.00,
    valorAtual: 11950.00,
    valorizacao: -450.00,
    tipo: 'Renda Fixa',
    subtipo: 'Tesouro Direto',
    vencimento: '15/05/2035',
    mesReferencia: 'Maio',
    alerta: true
  },
  {
    id: 'asset-30',
    corretora: 'XP Investimentos',
    displayName: 'Debênture Incentivada Cemig 12.5%',
    observacao: 'Debênture de Infraestrutura Isenta',
    valorAnterior: 14000.00,
    valorAtual: 14720.00,
    valorizacao: 720.00,
    tipo: 'Renda Fixa',
    subtipo: 'Debêntures',
    vencimento: '15/05/2031',
    mesReferencia: 'Maio',
    alerta: false
  },
  {
    id: 'asset-31',
    corretora: 'XP Investimentos',
    displayName: 'Ação Itau Unibanco PN',
    observacao: 'ITUB4 - Setor Financeiro',
    valorAnterior: 18450.00,
    valorAtual: 19820.00,
    valorizacao: 1370.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'ITUB4'
  },
  {
    id: 'asset-32',
    corretora: 'XP Investimentos',
    displayName: 'BBDC4 - Bradesco PN',
    observacao: 'Ação Preferencial de Baixa Volatilidade',
    valorAnterior: 12200.00,
    valorAtual: 11540.00,
    valorizacao: -660.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'BBDC4'
  },
  {
    id: 'asset-33',
    corretora: 'Banco Inter',
    displayName: 'ALZR11 - Alianza Trust FII',
    observacao: 'Fundo Imobiliário Multiestratégia',
    valorAnterior: 9100.00,
    valorAtual: 9020.00,
    valorizacao: -80.00,
    tipo: 'Renda Variável',
    subtipo: 'FII',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false,
    codigoB3: 'ALZR11'
  },
  {
    id: 'asset-34',
    corretora: 'Nubank',
    displayName: 'Ação Ordinária Sem Código',
    observacao: 'Ação de empresa de capital fechado',
    valorAnterior: 4000.00,
    valorAtual: 4200.00,
    valorizacao: 200.00,
    tipo: 'Renda Variável',
    subtipo: 'Ação Nacional',
    vencimento: 'Sem Vencimento',
    mesReferencia: 'Maio',
    alerta: false
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 't-1',
    data: '2026.05.07',
    tipo: 'Compra',
    valor: 10000.00,
    assetName: 'LCI de 91.5% do CDI (Nubank)'
  },
  {
    id: 't-2',
    data: '2026.05.07',
    tipo: 'Compra',
    valor: 60000.00,
    assetName: 'CDB de 100% do CDI (Nubank)'
  },
  {
    id: 't-3',
    data: '2026.05.06',
    tipo: 'Compra',
    valor: 10000.00,
    assetName: 'CDB de 87.0% do CDI (Banco Inter)'
  }
];

export const CORRETORAS_LIST = [
  'Banco BMG',
  'Nubank',
  'Banco Inter',
  'XP Investimentos',
  'C.E.F.',
  'Sofisa',
  'BTG Pactual'
];

export const MESES_LIST = [
  'Janeiro',
  'Fevereiro',
  'Março',
  'Abril',
  'Maio',
  'Junho',
  'Julho',
  'Agosto',
  'Setembro',
  'Outubro',
  'Novembro',
  'Dezembro'
];

// Subtypes corresponding to categories mapping
export const SUBTYPES_MAP: Record<string, string[]> = {
  'Renda Fixa': ['CDB', 'LCI', 'LCA', 'CRI', 'CRA', 'Tesouro Direto', 'Debêntures'],
  'Renda Variável': ['FII', 'Ação Nacional', 'Ação Internacional', 'ETF'],
  'Fundos': ['Ação', 'Multimercado', 'Previdência']
};
