package com.eferraz.pokedex.repository

import com.eferraz.pokedex.entities.BrokerageFirm
import com.eferraz.pokedex.entities.FixedIncome
import com.eferraz.pokedex.entities.FixedIncomeType
import com.eferraz.pokedex.entities.IssuerBank
import com.eferraz.pokedex.entities.Liquidity
import com.eferraz.pokedex.entities.Owner
import com.eferraz.pokedex.entities.ProfitabilityIndex
import kotlinx.datetime.LocalDate
import org.koin.core.annotation.Single

internal interface FixedIncomeRepository {
    fun get(): List<FixedIncome>
}

@Single
internal class FixedIncomeRepositoryImpl : FixedIncomeRepository {

    override fun get(): List<FixedIncome> {

        return listOf(
//            FixedIncome(
//                owner = Owner(name = "Enir"),
//                brokerageFirm = BrokerageFirm(name = "Futuro"),
//                description = "Aportes",
//                investedAmount = 0.0,
//                currentAmount = 7000*14+10000.0,
//                purchaseDate = LocalDate(2023, 5, 9),
//                maturityDate = LocalDate(2026, 5, 11),
//                profitability = 0f,
//                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
//                type = FixedIncomeType(name = "CDB"),
//                liquidity = Liquidity.DAILY,
//                issuerBank = IssuerBank(name = "Futuro"),
//            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "SUPER POUP BMG",
                investedAmount = 6000.0,
                currentAmount = 7895.86,
                purchaseDate = LocalDate(2023, 5, 9),
                maturityDate = LocalDate(2026, 5, 11),
                profitability = 110f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "CDB ESCALONADO",
                investedAmount = 20000.0,
                currentAmount = 20334.41,
                purchaseDate = LocalDate(2025, 8, 29),
                maturityDate = LocalDate(2027, 8, 29),
                profitability = 110f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "CDB ESCALONADO",
                investedAmount = 32019.77,
                currentAmount = 34722.25,
                purchaseDate = LocalDate(2025, 4, 1),
                maturityDate = LocalDate(2030, 4, 1),
                profitability = 112f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "CDB ESCALONADO",
                investedAmount = 30000.0,
                currentAmount = 32011.0,
                purchaseDate = LocalDate(2025, 4, 2),
                maturityDate = LocalDate(2030, 4, 2),
                profitability = 112f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "CDB ESCALONADO",
                investedAmount = 20000.0,
                currentAmount = 20216.78,
                purchaseDate = LocalDate(2025, 9, 15),
                maturityDate = LocalDate(2030, 9, 15),
                profitability = 106f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "BMG"),
                description = "CDB PRE",
                investedAmount = 10000.0,
                currentAmount = 12753.73,
                purchaseDate = LocalDate(2023, 10, 18),
                maturityDate = LocalDate(2025, 10, 18),
                profitability = 12.96f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "BMG"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "Caixinha Turbo Ultravioleta",
                investedAmount = 10000.0,
                currentAmount = 10000.0,
                purchaseDate = LocalDate(2025, 10, 18),
                maturityDate = LocalDate(2030, 10, 18),
                profitability = 120f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "RDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "Nubank"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "Saldo Separado",
                investedAmount = 102718.46,
                currentAmount =102718.46,
                purchaseDate = LocalDate(2000, 1, 1),
                maturityDate = LocalDate(2050, 1, 1),
                profitability = 100f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "RDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "Nubank"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "LCA BANCO ABC BRASIL",
                investedAmount = 5000.0,
                currentAmount = 5025.0,
                purchaseDate = LocalDate(2025, 10, 3),
                maturityDate = LocalDate(2026, 7, 1),
                profitability = 90.5f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "LCA"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "ABC Brasil"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB BANCO DIGIMAIS",
                investedAmount = 3000.0,
                currentAmount = 4443.91,
                purchaseDate = LocalDate(2021, 8, 4),
                maturityDate = LocalDate(2026, 7, 9),
                profitability = 11.29f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Digimais"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB DM FINANCEIRA",
                investedAmount = 3161.70,
                currentAmount = 3215.70,
                purchaseDate = LocalDate(2025, 8, 29),
                maturityDate = LocalDate(2027, 5, 3),
                profitability = 113f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "DM Financeira"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB BANCO SEMEAR SA",
                investedAmount = 2000.0,
                currentAmount = 3059.67,
                purchaseDate = LocalDate(2022, 6, 29),
                maturityDate = LocalDate(2027, 6, 3),
                profitability = 122f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Semear"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB BANCO MASTER",
                investedAmount = 3021.87,
                currentAmount = 4246.98,
                purchaseDate = LocalDate(2023, 1, 30),
                maturityDate = LocalDate(2028, 12, 26),
                profitability = 15.5f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB BANCO MASTER",
                investedAmount = 3000.0,
                currentAmount = 4214.51,
                purchaseDate = LocalDate(2023, 1, 30),
                maturityDate = LocalDate(2029, 1, 2),
                profitability = 121f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(

                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Nubank"),
                description = "CDB BANCO MASTER",
                investedAmount = 5000.0,
                currentAmount = 6840.90,
                purchaseDate = LocalDate(2023, 5, 10),
                maturityDate = LocalDate(2029, 4, 9),
                profitability = 125f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LCA ORIGINAL",
                investedAmount = 51000.0,
                currentAmount = 54162.95,
                purchaseDate = LocalDate(2025, 5, 5),
                maturityDate = LocalDate(2026, 5, 4),
                profitability = 93f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "LCA"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Original"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LCI ORIGINAL",
                investedAmount = 20000.0,
                currentAmount = 21281.91,
                purchaseDate = LocalDate(2025, 4, 28),
                maturityDate = LocalDate(2026, 4, 27),
                profitability = 93f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "LCI"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Original"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LCI BRB",
                investedAmount = 17000.0,
                currentAmount = 17000.35,
                purchaseDate = LocalDate(2025, 10, 16),
                maturityDate = LocalDate(2026, 10, 16),
                profitability = 91.5f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "LCI"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "BRB"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LCI IPCA 252 TB BANCO BARI",
                investedAmount = 12644.01,
                currentAmount = 13141.18,
                purchaseDate = LocalDate(2022, 12, 23),
                maturityDate = LocalDate(2025, 12, 22),
                profitability = 5.1f,
                profitabilityIndex = ProfitabilityIndex.INFLATION_LINKED,
                type = FixedIncomeType(name = "LCI"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Bari"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LCI IPCA FINAL 3 ANOS",
                investedAmount = 2500.0,
                currentAmount = 3131.28,
                purchaseDate = LocalDate(2023, 5, 29),
                maturityDate = LocalDate(2026, 5, 29),
                profitability = 5.28f,
                profitabilityIndex = ProfitabilityIndex.INFLATION_LINKED,
                type = FixedIncomeType(name = "LCI"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Inter"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "CDB ARBI",
                investedAmount = 10000.0,
                currentAmount = 10991.14,
                purchaseDate = LocalDate(2025, 1, 14),
                maturityDate = LocalDate(2029, 1, 12),
                profitability = 115f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "ARBI"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "CDB IPCA 252 TB BANCO MASTER",
                investedAmount = 4482.72,
                currentAmount = 4437.18,
                purchaseDate = LocalDate(2021, 11, 18),
                maturityDate = LocalDate(2026, 11, 17),
                profitability = 6.5f,
                profitabilityIndex = ProfitabilityIndex.INFLATION_LINKED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "CDB IPCA 252 TB BANCO MASTER",
                investedAmount = 4309.82,
                currentAmount = 4298.23,
                purchaseDate = LocalDate(2022, 4, 11),
                maturityDate = LocalDate(2027, 4, 12),
                profitability = 7.28f,
                profitabilityIndex = ProfitabilityIndex.INFLATION_LINKED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "CDB IPCA 252 TB BANCO MASTER",
                investedAmount = 3027.42,
                currentAmount = 3065.49,
                purchaseDate = LocalDate(2022, 6, 3),
                maturityDate = LocalDate(2027, 6, 28),
                profitability = 15.9f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "CDB DI FLUT TB BANCO MASTER",
                investedAmount = 1505.17,
                currentAmount = 1532.39,
                purchaseDate = LocalDate(2022, 4, 4),
                maturityDate = LocalDate(2027, 3, 10),
                profitability = 115f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Banco Master"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Inter"),
                description = "LIG LIQUIDEZ",
                investedAmount = 14999.98,
                currentAmount = 15033.86,
                purchaseDate = LocalDate(2025, 10, 3),
                maturityDate = LocalDate(2027, 9, 3),
                profitability = 87f,
                profitabilityIndex = ProfitabilityIndex.POST_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "Inter"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "FGTS"),
                description = "FGTS",
                investedAmount = 0.0,
                currentAmount = 104319.30,
                purchaseDate = LocalDate(2000, 1, 1),
                maturityDate = LocalDate(2026, 12, 31),
                profitability = 0f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "FGTS"),
                liquidity = Liquidity.AT_MATURITY,
                issuerBank = IssuerBank(name = "FGTS"),
            ),
            FixedIncome(
                owner = Owner(name = "Enir"),
                brokerageFirm = BrokerageFirm(name = "Sofisa"),
                description = "CDB LIQUIDEZ DIARIA",
                investedAmount = 10000.0,
                currentAmount = 12625.05,
                purchaseDate = LocalDate(2023, 9, 8),
                maturityDate = LocalDate(2026, 9, 8),
                profitability = 110f,
                profitabilityIndex = ProfitabilityIndex.PRE_FIXED,
                type = FixedIncomeType(name = "CDB"),
                liquidity = Liquidity.DAILY,
                issuerBank = IssuerBank(name = "Sofisa"),
            )
        )
    }
}